# Generated by Django 4.1.3 on 2022-11-09 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_product_favorire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorire',
            new_name='Favorite',
        ),
    ]
