# Generated by Django 4.1.3 on 2022-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_isfavorit_favorite_isfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marcket_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0.0),
        ),
    ]
