# Generated by Django 4.1.3 on 2022-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price_old',
            field=models.FloatField(default=0.0),
        ),
    ]
